export const SESSIONS_LIST_LOAD = 'SESSIONS_LIST_LOAD';
export const SINGLE_SESSION_LOAD = 'SINGLE_SESSION_LOAD';

export const OVERVIEW_TIMES_LOAD = 'OVERVIEW_TIMES_LOAD';
export const OVERVIEW_ERRORS = 'OVERVIEW_ERRORS';








export const COMPONENT_DOCUMENTATION_LOAD = 'COMPONENT_DOCUMENTATION_LOAD';
export const COMPONENT_DOCUMENTATION_UNLOAD = 'COMPONENT_DOCUMENTATION_UNLOAD';

export const MARKDOWN_LIST_FILTER = 'MARKDOWN_LIST_FILTER';
export const MARKDOWN_DOCUMENTATION_LOAD = 'MARKDOWN_DOCUMENTATION_LOAD';

export const DEMO_LIST_FILTER = 'DEMO_LIST_FILTER';
export const DEMO_DOCUMENTATION_LOAD = 'DEMO_DOCUMENTATION_LOAD';
